[package]
name = "docs_rs_admin"
version = "0.6.0"
authors = ["Onur Aslan <onuraslan@gmail.com>", "The Rust Project Developers"]
license = "MIT"
repository = "https://github.com/rust-lang/docs.rs"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
docs_rs_repository_stats = { path = "../../lib/docs_rs_repository_stats" }
chrono = { workspace = true }
clap = { workspace = true }
docs_rs_build_limits = { path = "../../lib/docs_rs_build_limits" }
docs_rs_build_queue = { path = "../../lib/docs_rs_build_queue" }
docs_rs_context = { path = "../../lib/docs_rs_context" }
docs_rs_cargo_metadata = { path = "../../lib/docs_rs_cargo_metadata" }
docsrs-metadata = { path = "../../lib/metadata" }
docs_rs_registry_api = { path = "../../lib/docs_rs_registry_api" }
docs_rs_mimes = { path = "../../lib/docs_rs_mimes" }
zip = { workspace = true }
regex = { workspace = true }
docs_rs_database = { path = "../../lib/docs_rs_database" }
mime = { workspace = true }
docs_rs_fastly = { path = "../../lib/docs_rs_fastly" }
docs_rs_headers = { path = "../../lib/docs_rs_headers" }
docs_rs_logging = { path = "../../lib/docs_rs_logging" }
docs_rs_storage = { path = "../../lib/docs_rs_storage" }
docs_rs_types = { path = "../../lib/docs_rs_types" }
docs_rs_utils = { path = "../../lib/docs_rs_utils" }
futures-util = { workspace = true }
reqwest = { workspace = true }
async-tar = { version = "0.6.0", default-features = false, features = ["runtime-tokio", "xattr"]}
sqlx = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
bon = { workspace = true }
docs_rs_config = { path = "../../lib/docs_rs_config", features = ["testing"] }
docs_rs_context = { path = "../../lib/docs_rs_context", features = ["testing"] }
docs_rs_database = { path = "../../lib/docs_rs_database", features = ["testing"] }
docs_rs_opentelemetry = { path = "../../lib/docs_rs_opentelemetry", features = ["testing"] }
docs_rs_storage = { path = "../../lib/docs_rs_storage", features = ["testing"] }
docs_rs_test_fakes = { path = "../../lib/docs_rs_test_fakes" }
docs_rs_types = { path = "../../lib/docs_rs_types", features = ["testing"] }
pretty_assertions = { workspace = true }
test-case = { workspace = true }

